#cloud-config
package_update: true
package_upgrade: true

packages:
    - build-essential
    - libssl-dev
    - libffi-dev 
    - python3
    - python3-pip
    - awscli
    - unzip

write_files:
- content: |
    #!/usr/bin/env bash
    cd /home/ubuntu/
    pip3 install virtualenvwrapper kaggle --user
    export PATH="$HOME/.local/bin:$PATH"
    # Kaggle download dataset
    mkdir /home/ubuntu/.kaggle/
    aws s3 cp s3://m-secrets-us-east-2/kaggle.json /home/ubuntu/.kaggle/
    chmod 600 /home/ubuntu/.kaggle/kaggle.json
    kaggle datasets download -d paultimothymooney/chest-xray-pneumonia
    # github dataset download
    git clone https://github.com/ieee8023/covid-chestxray-dataset.git
    export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
    source ~/.local/bin/virtualenvwrapper.sh
    mkvirtualenv FLANNEL
    git clone https://github.com/qxiaobu/FLANNEL.git
    # copy dataset
    mkdir /home/ubuntu/FLANNEL/original\ data/covid-chestxray-dataset-master/
    mkdir /home/ubuntu/FLANNEL/original\ data/chest_xray
    cp /home/ubuntu/covid-chestxray-dataset/images/* /home/ubuntu/FLANNEL/original\ data/covid-chestxray-dataset-master/
    unzip chest-xray-pneumonia.zip -d /home/ubuntu/FLANNEL/original\ data/chest_xray
    # cd CourseProject/src
    # pip install -r requirements.txt
    # cd ../playground
    # python main.py > experiment1_output.txt
  path: /root/clone.sh
  

runcmd:
  - sudo cp /root/clone.sh /home/ubuntu/clone.sh
  - [ bash, -c, "chmod +x /home/ubuntu/clone.sh" ]
  - [ bash, -c, "chown ubuntu: /home/ubuntu/clone.sh" ]
  - sudo -u ubuntu bash -c 'whoami;/home/ubuntu/clone.sh'